Fixed translations, and removed unused file
PluginAndPartners/payment-magento-plugin pull request #69
Opened 2023-05-09 14:44 UTC by cleitonaguiarandrade

2023-05-09 16:00 UTC, dmsantosd requested changes

2023-05-09 16:00 UTC, dmsantosd commented on etc/di.xml
> +            <argument name="code" xsi:type="const">MercadoPago\PaymentMagento\Model\Ui\ConfigProviderTwoCc::CODE</argument>
O caminho deveria ser com o novo nome, certo?

```suggestion
            <argument name="code" xsi:type="const">MercadoPago\AdbPayment\Model\Ui\ConfigProviderTwoCc::CODE</argument>
```

2023-05-09 16:00 UTC, dmsantosd commented on etc/di.xml
> +            <argument name="infoBlockType" xsi:type="string">MercadoPago\PaymentMagento\Block\Sales\Info\TwoCc</argument>
O caminho deveria ser com o novo nome, certo?

```suggestion
            <argument name="infoBlockType" xsi:type="string">MercadoPago\ AdbPayment\Block\Sales\Info\TwoCc</argument>
```

2023-05-09 17:42 UTC, dmsantosd submitted a review, later dismissed

2023-05-12 15:39 UTC, katelucena-meli approved these changes

2023-05-12 21:10 UTC, mlafernandes approved these changes

2023-05-15 19:59 UTC, merged